version = "0.2.1"
content_dir = "content"

[html.assets]
copy = ["images/hero.jpg"]
js_scripts = "index.js"

[html.spine]
vertebrae = ["index.typ", "opening.typ", "closing.typ"]

[pdf.spine]
title = "[SCALE]: Software, Community, Territory"
vertebrae = ["index.typ"]
merge = true

[epub.spine]
title = "[SCALE]: Software, Community, Territory"
vertebrae = ["index.typ"]
